# Generated by Django 5.2.4 on 2025-07-23 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Darta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(help_text='Unique number within its fiscal year.', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('sender_receiver_info', models.CharField(help_text="Sender's details for Darta, Receiver's details for Chalani.", max_length=255)),
                ('document_type', models.CharField(choices=[('Letter', 'Letter'), ('Notice', 'Notice'), ('Report', 'Report'), ('Application', 'Application'), ('Other', 'Other')], default='Letter', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, help_text='Date after which the document might not be relevant.', null=True)),
                ('followup_date', models.DateField(blank=True, help_text='Date for necessary follow-up action.', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_file', models.FileField(blank=True, help_text='Upload the main document file.', null=True, upload_to='darta_files/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_documents', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='The fiscal year of the document.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_documents', to='settings_app.fiscalyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_documents', to='darta_chalani.department')),
            ],
            options={
                'verbose_name': 'Darta',
                'verbose_name_plural': 'Dartas',
                'ordering': ['-document_date', '-created_at'],
                'abstract': False,
                'default_related_name': 'darta_documents',
                'unique_together': {('document_number', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='Chalani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(help_text='Unique number within its fiscal year.', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('sender_receiver_info', models.CharField(help_text="Sender's details for Darta, Receiver's details for Chalani.", max_length=255)),
                ('document_type', models.CharField(choices=[('Letter', 'Letter'), ('Notice', 'Notice'), ('Report', 'Report'), ('Application', 'Application'), ('Other', 'Other')], default='Letter', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, help_text='Date after which the document might not be relevant.', null=True)),
                ('followup_date', models.DateField(blank=True, help_text='Date for necessary follow-up action.', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_file', models.FileField(blank=True, help_text='Upload the main document file.', null=True, upload_to='chalani_files/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_documents', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='The fiscal year of the document.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_documents', to='settings_app.fiscalyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_documents', to='darta_chalani.department')),
            ],
            options={
                'verbose_name': 'Chalani',
                'verbose_name_plural': 'Chalanis',
                'ordering': ['-document_date', '-created_at'],
                'abstract': False,
                'default_related_name': 'chalani_documents',
                'unique_together': {('document_number', 'fiscal_year')},
            },
        ),
    ]
