# Generated by Django 5.2.4 on 2025-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_ad', models.DateField(help_text='Start date of the fiscal year in AD (e.g., 2023-07-16 for 2080/81 BS)', unique=True)),
                ('end_date_ad', models.DateField(help_text='End date of the fiscal year in AD (e.g., 2024-07-15 for 2080/81 BS)', unique=True)),
                ('name', models.CharField(blank=True, help_text='Nepali Fiscal Year Name (e.g., 2080/81 BS). Will be auto-generated if left blank.', max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Set as the currently active fiscal year for Darta/Chalani. Only one can be active.')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date_ad'],
            },
        ),
    ]
